<a href="https://colab.research.google.com/github/archue001/18-comic-finder/blob/master/LA_%E7%BF%92%E9%A1%8C%E7%AF%84%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 與 Jupyter Notebook 操作練習 — 作業交卷說明
- 學生名字: 林耀鈴 學號: s01234567 班級: 資工1C
- 交卷日期: 2023/10/00
- 連結: https://t.ly/jZbEA (re: [short url](https://chrome.google.com/webstore/detail/url-shortener/oodfdmglhbbkkcngodjjagblikmoegpa)) ![](http://chart.apis.google.com/chart?cht=qr&chs=80x80&chld=H|0&chl=https://t.ly/jZbEA)

## 簡介:
- 這個習題是為了讓你練習 Python, Jupyter Notebook  與 Google Colab 使用方法。
- Jupyter Notebook: https://jupyter.org/.
- Google Colab: https://colab.research.google.com/notebooks/welcome.ipynb to learn some Colab usage.
- This is a Jupyiter notebook presentation. Jupyiter notebook是用來編寫python程式碼的*（但現在已經支持其他語言）。 Jupyiter有很多項優點，其中一項就是可以在內部寫Markdown 語法，不需要在另外用一份文檔說明程式碼或是寫很多的註解來說明程式碼。

- [Linear algebra with Numpy ](https://colab.research.google.com/github/drvinceknight/Python-Mathematics-Handbook/blob/master/02-Linear-algebra-with-Numpy.ipynb) is a Python language software package for linear algebra;
- [Linear algebra in Machine Learning](https://colab.research.google.com/github/adhiraiyan/DeepLearningWithTF2.0/blob/master/notebooks/02.00-Linear-Algebra.ipynb)
中文教學: [Link1](https://medium.com/pyradise/%E4%BD%BF%E7%94%A8-python-%E4%BE%86%E8%AA%8D%E8%AD%98%E7%9F%A9%E9%99%A3-915376207187)


## **習題說明:**
1. 將本習題範本 copy 到您自己的 google drive 雲端硬碟，建議檔名為： [your-std-id].ipynb
1. 請更改第一個 cell 內容中的日期資料，並將學生名字設為你的名字。
1. 首先**執行**下面這格程式，請輸入 **std_id = 你的學號**。
1. 請保留前面內容順訊，但請根據輸出的隨機順序, **調換更動本ipynb檔案的內容順序。**
1. 記得將您的 ipynb 檔案按滑鼠右鍵，點選「共用」，權限改成:**「分享給知道連結的人」**,老師才能測試您的作業。
1. 利用 Runtime -> Run all (ctl-F9)，一次執行完畢後利用 File -> Print(ctl-P)產生 PDF檔後更名為 [your-id].PDF (e.g. s01234567.pdf)
1. **交作業時請繳交PDF檔**.


In [ ]:
# Set random seed to decide your output orderings
import numpy as np
import random
std_id = 1234567
np.random.seed(std_id)
print ( np.random.permutation(list('ABCDE')) )

['B' 'C' 'A' 'E' 'D']


In [ ]:
# Sect B -- Expressions

hourly_salary = 125                     # 設定時薪
annual_salary = hourly_salary * 8 * 300         # 計算年薪
monthly_fee = 9000                     # 設定每月花費
annual_fee = monthly_fee * 12               # 計算每年花費
annual_savings = annual_salary - annual_fee       # 計算每年儲存金額
print(annual_savings)                    # 列出每年儲存金額

192000


In [ ]:
# Sect C -- 資料型態

x = 10
print(x)
print(type(x))      # 加法前列出x資料型態
x = x + 5.5
print(x)
print(type(x))      # 加法後列出x資料型態

10
<class 'int'>
15.5
<class 'float'>


In [ ]:
# Sect A -- Python Basics

print("Hello! Python")   # 列印字串

Hello! Python


In [ ]:
# Sect E -- List

james = [23, 19, 22, 31, 18]        # 定義james的5場比賽得分
games = len(james)                  # 獲得場次數據
print("經過 %d 比賽最高得分 = " % games, max(james))
print("經過 %d 比賽最低得分 = " % games, min(james))
print("經過 %d 比賽得分總計 = " % games, sum(james))

經過 5 比賽最高得分 =  31
經過 5 比賽最低得分 =  18
經過 5 比賽得分總計 =  113


In [ ]:
# Sect D -- formatted print

r = 5
PI = 3.14159
area = PI * r ** 2
print("/半徑{0:3d}圓面積是{1:10.2f}/".format(r,area))
print("/半徑{0:>3d}圓面積是{1:>10.2f}/".format(r,area))
print("/半徑{0:<3d}圓面積是{1:<10.2f}/".format(r,area))
print("/半徑{0:^3d}圓面積是{1:^10.2f}/".format(r,area))

/半徑  5圓面積是     78.54/
/半徑  5圓面積是     78.54/
/半徑5  圓面積是78.54     /
/半徑 5 圓面積是  78.54   /


In [ ]:
import numpy as np

Now we can define $A$:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

We can obtain the following straightforwardly:

- $5A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$

In [ ]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [ ]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [ ]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [ ]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [ ]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A =
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

We can verify our result:

In [ ]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

## THE END
Here is the end of the ipython notebook code. Please add whatever that you feel comfortable.